title: electrikjesus blog
description: > # this means to ignore newlines until "baseurl:"
  Just s simple blog to place my thoughts and share through.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/electrikjesus

# Author Settings
author: Jon West # add your name
author-img: https://avatars.githubusercontent.com/u/8572619?v=4 # add your photo
about-author: I work to bring the dreams of those around me to reality. Founder & CTO of BlissLabs, Creator of Bliss OS, Android-Generic Project and contributor to even more. # add description
social-twitter: @electrikjesus
social-facebook: # add your Facebook handle
social-github: electrikjesus # add your Github handle
social-linkedin: electrikjesus
social-email: # add your Email address

# Disqus
discus-identifier: electrikjesus # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
